#! ---------------------------------------------------------------
#! Aurora Theme for Hexo
#! ---------------------------------------------------------------

site:
  subtitle: ""
  author: "Mclarenlife"
  nick: "LXJ"
  description: "..."
  language: en
  avatar: "https://ik.imagekit.io/n0ytbt1j3/avatar/%E9%AB%98%E6%B8%85%E9%87%8D%E5%88%B6%E5%8E%9F%E7%89%88.jpg?updatedAt=1728457808170"
  logo: "https://ik.imagekit.io/n0ytbt1j3/avatar/%E6%9C%AA%E6%A0%87%E9%A2%98-1.png?updatedAt=1732620816093"



menu:
  About: true
  Tags: true
  Archives: true
  Friends: false

theme:
  dark_mode: false
  profile_shape: diamond
  feature: true

site_meta:
  cdn: cn
  favicon: ""
  description: ""
  keywords: ""
  author: ""

shiki:
  enable: true
  backgroundColor: "#1a1a1a"
