const pad=n=>String(n).padStart(2,'0');
function plate(src,title,hero=false){return `<figure class="flight-plate${hero?' flight-hero-plate':''}"><button class="photo-button" data-photo="${src}" data-caption="${title} · 原创教学示意" aria-label="放大示意图：${title}"><img src="${src}" alt="${title}" width="1000" height="700" ${hero?'fetchpriority="high"':'loading="lazy"'}><span class="photo-zoom">＋</span></button><figcaption>FLIGHT STUDY / ${title} <span>点击放大 ↗</span></figcaption></figure>`}
export function windComponents(speed,angle){const radians=angle*Math.PI/180;return{head:speed*Math.cos(radians),cross:speed*Math.sin(radians)}}
function windLab(){return `<section class="wind-lab" aria-labelledby="wind-title"><header><span class="flight-label">DESK EXPERIMENT / 风的分量</span><h2 id="wind-title">同一阵风，两个方向。</h2><p>跑道朝上。角度表示来风相对跑道方向：正值从右侧来，负值从左侧来；0° 为正逆风，±180° 为正顺风。</p></header><div class="wind-lab-grid"><div class="wind-controls"><label for="wind-speed">风速 <output data-wind-speed>20 kt</output></label><input id="wind-speed" type="range" min="0" max="40" value="20"><label for="wind-angle">来风相对角 <output data-wind-angle>+30°</output></label><input id="wind-angle" type="range" min="-180" max="180" step="5" value="30"><div class="wind-readouts" aria-live="polite"><p><span data-head-label>逆风分量</span><strong data-head-value>17.3 kt</strong></p><p><span data-cross-label>右侧来风分量</span><strong data-cross-value>10.0 kt</strong></p></div></div><svg class="wind-display" viewBox="0 0 320 320" role="img" aria-label="跑道方向与来风矢量的动态分解图"><defs><marker id="wind-tip" markerWidth="7" markerHeight="7" refX="5" refY="3" orient="auto"><path d="M0 0L6 3L0 6" fill="none" stroke="#e8af65"/></marker></defs><circle cx="160" cy="160" r="120" fill="none" stroke="#5c8193" stroke-dasharray="3 8"/><rect x="138" y="54" width="44" height="212" rx="5" fill="#37566b"/><path d="M160 65V255" stroke="#d8e5e7" stroke-dasharray="12 10"/><path data-wind-projection d="M187.5 112.4H160V160" fill="none" stroke="#94c5c2" stroke-dasharray="4 4"/><path data-wind-arrow d="M187.5 112.4L160 160" stroke="#e8af65" stroke-width="4" marker-end="url(#wind-tip)"/><circle data-wind-origin cx="187.5" cy="112.4" r="4" fill="#e8af65"/><text x="160" y="28" text-anchor="middle">跑道方向 ↑</text><text x="160" y="302" text-anchor="middle">箭头指向风吹去的方向</text></svg></div><small>固定风的几何分解，方向采用同一基准。非偏流修正角、蹬舵量或起降许可判断；未纳入阵风、机型限制与跑道条件。</small></section>`}
export function updateWindLab(root=document){
 const lab=root.querySelector('.wind-lab');if(!lab)return;
 const speed=Number(lab.querySelector('#wind-speed').value),angle=Number(lab.querySelector('#wind-angle').value),{head,cross}=windComponents(speed,angle);
 const clean=n=>Math.abs(n)<.05?0:n;
 lab.querySelector('[data-wind-speed]').textContent=`${speed} kt`;
 lab.querySelector('[data-wind-angle]').textContent=`${angle>0?'+':''}${angle}°`;
 lab.querySelector('[data-head-label]').textContent=clean(head)<0?'顺风分量':'逆风分量';
 lab.querySelector('[data-cross-label]').textContent=clean(cross)===0?'无侧风':cross>0?'右侧来风分量':'左侧来风分量';
 lab.querySelector('[data-head-value]').textContent=`${Math.abs(clean(head)).toFixed(1)} kt`;
 lab.querySelector('[data-cross-value]').textContent=`${Math.abs(clean(cross)).toFixed(1)} kt`;
 const x=160+cross*2.75,y=160-head*2.75;
 lab.querySelector('[data-wind-arrow]').setAttribute('d',`M${x} ${y}L160 160`);
 lab.querySelector('[data-wind-projection]').setAttribute('d',`M${x} ${y}H160V160`);
 lab.querySelector('[data-wind-origin]').setAttribute('cx',x);lab.querySelector('[data-wind-origin]').setAttribute('cy',y);
}
export function flightContent(a){return `<div class="flight-folio"><span>MCLARY / FLIGHT SCHOOL</span><span>GROUND STUDY — ${a.code}</span></div><header class="flight-hero"><div><p class="flight-label">${a.subtitle}</p><h2>${a.hero.join('<br>')}</h2><p class="flight-lead">${a.lead}</p><div class="flight-stamp">FLIGHT NOTES<span>地面学习 · 模拟训练</span></div></div>${plate(a.portrait,a.portraitAlt,true)}</header><div class="flight-brief"><span class="flight-brief-code">BRIEF<br><b>${a.code}</b></span><div><h3>本次学习任务</h3><p>${a.brief.join(' <span aria-hidden="true">／</span> ')}</p></div><span class="flight-duration">${a.chapters.length} 节笔记<br>约 ${a.minutes} 分钟</span></div><p class="flight-context">以常规固定翼飞机原理为主，适合地面学习与模拟飞行。真实飞行须接受合格教员训练，依据机型 AFM / POH、当地规则与有效程序；本页不提供可直接套用的操作速度或检查单。</p><nav class="flight-contents" aria-label="本档案目录">${a.chapters.map((c,i)=>`<a href="#flight-${a.code}-${i+1}"><span>${pad(i+1)}</span>${c.title}<b aria-hidden="true">↗</b></a>`).join('')}</nav><blockquote class="flight-principle"><span>KEEP IN MIND</span>${a.principle}</blockquote>${a.lab==='wind'?windLab():''}${a.chapters.map((c,i)=>`<section class="flight-chapter" id="flight-${a.code}-${i+1}"><header><span class="flight-chapter-number">${pad(i+1)}</span><div><p class="flight-label">${c.label}</p><h2>${c.title}</h2></div></header><div class="flight-body"><div class="flight-prose">${c.paragraphs.map(p=>`<p>${p}</p>`).join('')}<details class="flight-question"><summary>${c.question}<span aria-hidden="true">＋</span></summary><p>${c.answer}</p></details></div><aside class="flight-note"><small>INSTRUCTOR'S NOTE</small><p>${c.note}</p><span aria-hidden="true">✳ 留给下一次练习</span></aside></div>${i===1||i===3?plate(c.art,c.title):''}<div class="flight-exercise"><h3>SIM SESSION <span>模拟练习 ${a.code}.${pad(i+1)}</span></h3><ol>${c.exercise.map(e=>`<li>${e}</li>`).join('')}</ol></div></section>`).join('')}<section class="flight-log"><div><span class="flight-label">AFTER FLIGHT / 复盘页</span><h2>把一次飞行，<br>变成下一次的准备。</h2><p>用几行事实，代替一句“今天飞得还行”。</p></div><dl>${[['场景','机型 · 天气 · 任务 · 所用资料'],['线索','什么时候看见了什么变化？'],['决定','为什么选择这个动作或方案？'],['反馈','实际结果和预期有什么差别？'],['下次','一个具体、可验证的练习目标']].map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl></section>`}
