const number=n=>String(n).padStart(2,'0');
function plate(src,title,caption,hero=false){return `<figure class="race-plate${hero?' race-hero-plate':''}"><button class="photo-button" data-photo="${src}" data-caption="${title} · 原创概念示意" aria-label="放大示意图：${title}"><img src="${src}" alt="${title}" width="1000" height="700" ${hero?'fetchpriority="high"':'loading="lazy"'}><span class="photo-zoom">＋</span></button><figcaption>${caption}</figcaption></figure>`}
function gripLab(){return `<section class="grip-lab" aria-labelledby="grip-title"><div><span class="race-eyebrow">INTERACTIVE / 抓地预算</span><h2 id="grip-title">给转向多一点，<br>纵向还剩多少？</h2><p>拖动滑块，观察理想圆形包络内的力分配。这里把总能力归一化为 100%，不区分制动与加速的真实差异。</p><label for="grip-demand">横向需求 <output data-grip-lateral>60%</output></label><input id="grip-demand" type="range" min="0" max="100" value="60" step="1"><p class="grip-result">理论纵向余量 <output data-grip-remaining>80%</output></p></div><div class="grip-plot"><svg viewBox="0 0 320 320" role="img" aria-label="理想抓地圆中横向需求与纵向余量的关系"><circle cx="160" cy="160" r="113" fill="#2f4547" stroke="#9cb8ad"/><path d="M25 160H295M160 25V295" stroke="#8d9c97"/><path data-grip-vector d="M160 160L227.8 69.6" stroke="#ed794b" stroke-width="4" fill="none"/><path data-grip-guides d="M160 160H227.8V69.6" stroke="#e5c44f" stroke-dasharray="5 5" fill="none"/><circle data-grip-point cx="227.8" cy="69.6" r="6" fill="#f7e6b9"/><text x="165" y="20">纵向</text><text x="265" y="184">横向</text></svg><p>√(1 − 横向需求²)</p></div><small>理想化示意，不是实测轮胎曲线、踏板比例或车辆安全阈值。真实边界受轮胎、载荷和环境影响。</small></section>`}
export function updateGripLab(root=document){
 const lab=root.matches?.('.grip-lab')?root:root.querySelector('.grip-lab');if(!lab)return;
 const x=Number(lab.querySelector('input').value)/100,y=Math.sqrt(Math.max(0,1-x*x));
 const px=160+x*113,py=160-y*113;
 lab.querySelector('[data-grip-lateral]').textContent=`${Math.round(x*100)}%`;
 lab.querySelector('[data-grip-remaining]').textContent=`${Math.round(y*100)}%`;
 lab.querySelector('[data-grip-vector]').setAttribute('d',`M160 160L${px} ${py}`);
 lab.querySelector('[data-grip-guides]').setAttribute('d',`M160 160H${px}V${py}`);
 lab.querySelector('[data-grip-point]').setAttribute('cx',px);lab.querySelector('[data-grip-point]').setAttribute('cy',py);
}
export function racingContent(a){return `<div class="race-topline"><span>RACING / DRIVER'S FIELD NOTES</span><span>VOL. ${a.code} — ${a.level}</span></div><header class="race-hero"><div><p class="race-eyebrow">MCLARY MOTORSPORT ARCHIVE</p><h2>${a.hero.join('<br>')}</h2><p class="race-lead">${a.lead}</p><div class="race-meta"><span>05 节驾驶笔记</span><span>约 ${a.minutes} 分钟</span><span>入门 → 进阶</span></div></div>${plate(a.portrait,a.portraitAlt,`PLATE ${a.code} / 放大查看标注`,true)}</header><p class="race-context">适用：模拟赛车与有教练指导的封闭赛道训练。图示为概念模型；实际操作依据车辆、轮胎与现场条件。</p><nav class="race-contents" aria-label="本档案目录">${a.chapters.map((c,i)=>`<a href="#race-${a.code}-${i+1}"><span>${number(i+1)}</span>${c.title}<b aria-hidden="true">↗</b></a>`).join('')}</nav><blockquote class="race-pullquote"><span>THE WORKING PRINCIPLE</span>${a.takeaway}</blockquote>${a.lab==='grip'?gripLab():''}<div class="race-chapters">${a.chapters.map((c,i)=>`<section class="race-chapter" id="race-${a.code}-${i+1}"><header><span class="race-section-number">${number(i+1)}</span><div><p class="race-eyebrow">${c.kicker}</p><h2>${c.title}</h2></div></header><div class="race-chapter-grid"><div class="race-prose">${c.body.map(p=>`<p>${p}</p>`).join('')}<details class="race-diagnosis"><summary>${c.question}<span aria-hidden="true">＋</span></summary><p>${c.answer}</p></details></div><aside class="race-sticky"><span class="race-tape" aria-hidden="true"></span><small>ENGINEER'S NOTE / ${number(i+1)}</small><p>${c.note}</p><span class="race-scribble" aria-hidden="true">remember this ↗</span></aside></div>${i===1||i===3||(a.code==='03'&&i===4)?plate(c.diagram,c.title,`FIG. ${a.code}.${number(i+1)} / ${c.kicker}`):''}<div class="race-drill"><h3><span aria-hidden="true">↳</span> 下一组练习</h3><ol>${c.drill.map(d=>`<li>${d}</li>`).join('')}</ol></div></section>`).join('')}</div><section class="race-debrief"><div><span class="race-eyebrow">KEEP A RECORD / 带走一张复盘卡</span><h2>下一次，上车前读一遍。</h2><p>把感受变成可验证的观察。你可以复制这五个栏目，写进自己的练习记录。</p></div><dl>${[['条件','车 / 胎 / 天气 / 油量'],['目标','一个弯 · 一个阶段 · 一个问题'],['观察','实际发生了什么？'],['尝试','这次只改变了什么？'],['下一步','保留 / 撤回 / 再验证']].map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl></section>`}
