import {colorContent} from './color-view.js';
import {flightContent} from './flight-view.js';
import {racingContent} from './racing-view.js';
import {colorLabView} from './color-lab.js';
import {groups, architects, byId} from './data.js';
export const tab = (a,active=false) => `<a class="folder-tab${active?' active':''}" href="/cases/${a.id}" ${active?'aria-current="page"':''} style="--tab:${a.color};--ink:${a.ink || '#f5f2e9'}">${a.name}</a>`;
export function footer() { return `<footer class="archive-footer"><span class="scale" aria-hidden="true"><i></i><small>0 &nbsp;4 &nbsp;8 &nbsp;16 &nbsp;&nbsp;&nbsp;32</small></span><span>© 2026</span><span>INSPIRED BY <a href="https://www.mosbyfiles.com/" target="_blank" rel="noreferrer">MOSBY’S FILES</a></span></footer>`; }
export function homeView() {
 return `<section class="intro"><h1 class="curiosity-title" aria-label="FOLLOW YOUR CURIOSITY">${"FOLLOW YOUR CURIOSITY".split(" ").map(word=>`<span class="curiosity-word" aria-hidden="true">${[...word].map(letter=>`<span class="curiosity-letter"><span>${letter}</span></span>`).join('')}</span>`).join(' ')}</h1></section><div class="archive">${groups.map((g,i)=>`<section class="folder-group" style="--folder:${g.color};--order:${i};--file-count:${g.ids.length}" data-group="${i}" data-files="${g.ids.length}"><div class="folder-back">${g.ids.map((id,j)=>`<div class="file-leaves${j===0?' is-default':''}" data-file="${id}" style="--leaf-color:${byId[id].color};--leaf-order:${g.ids.length-j}" aria-hidden="true"><span class="folder-back-sheet"></span><span class="folder-front-sheet"></span></div>`).join('')}<nav class="folder-tabs" aria-label="${g.title}">${g.ids.map(id=>tab(byId[id])).join('')}</nav></div><div class="folder-surface"><span class="category-label">${g.title}</span></div></section>`).join('')}<div class="archive-bottom" style="--archive-base:${groups.at(-1).color}"><div class="compass-row" aria-hidden="true">${[0,1,2,3,4,5,6].map((v)=>`<span class="compass compass-${v}"><i></i><b>N</b></span>`).join('')}</div>${footer()}</div></div>`;
}
function biography(a) {
 if(a.kind==='lesson')return `<div class="biography"><aside class="identity"><figure class="portrait"><img src="${a.portrait}" alt="${a.portraitAlt}" width="800" height="680" fetchpriority="high"><span class="paperclip" aria-hidden="true"></span></figure><dl>${a.facts.map(([label,text])=>`<dt>${label}</dt><dd>${text}</dd>`).join('')}</dl><span class="archive-stamp">MCLARY‘S FILES<br>${a.topic||'摄影'}学习档案 / ${a.level||'入门篇'}</span></aside><div class="biography-copy"><p class="lesson-kicker">${a.topicCode||'PHOTOGRAPHY'} / FIELD NOTES</p><p class="lead">${a.lead}</p><p>${a.body}</p><p class="handwriting">${a.note}</p></div></div>`;
 return `<div class="biography"><aside class="identity"><figure class="portrait"><img src="/assets/${a.id}-portrait.avif" alt="Portrait of ${a.name}" width="2670" height="3051" fetchpriority="high"><span class="paperclip" aria-hidden="true"></span></figure><dl><dt>Born:</dt><dd>${a.born}</dd><dt>Died:</dt><dd>${a.died}</dd></dl><span class="archive-stamp">AMERICAN MODERNISM<br>RESEARCH ARCHIVE / ${a.years}</span></aside><div class="biography-copy"><p class="lead">${a.lead}</p><p>${a.body}</p><p class="handwriting">${a.note}</p></div></div>`;
}
function lessonWork(a,w,i){
 return `<section class="work work-${i}"><div class="work-index">${String(i+1).padStart(2,'0')} / 学习笔记</div><figure class="archive-photo"><button class="photo-button" data-photo="${w[3]}" data-caption="${a.name} — ${w[0]} · 原创示意图" aria-label="放大示意图：${w[0]}"><img src="${w[3]}" alt="${w[0]}：${w[1]}示意图" loading="lazy" width="960" height="680"><span class="photo-zoom">＋</span></button><figcaption>${a.name} / ${w[1]} · 示意图</figcaption></figure><div class="note-card"><span class="note-pin" aria-hidden="true"></span><span class="lesson-subtitle">${w[1]}</span><h2>${w[0]}</h2><p>${w[2]}</p><div class="lesson-practice"><h3>动手试一试</h3><p>${w[4]}</p></div><span class="note-number">MCLARY / ${a.topicCode||'PHOTO'} ${String(i+1).padStart(2,'0')}</span></div></section>`;
}
function nextPreview(a) {
 return `<a class="next-folder-preview" href="/cases/${a.id}" aria-label="Continue to ${a.name}" style="--case:${a.color};--case-ink:${a.ink||'#f5f2e9'}"><h2 class="next-folder-title">${a.name}</h2><span class="next-folder-hint">Keep scrolling for the next collection ↓</span></a>`;
}
function standardContent(a) { return `${biography(a)}${a.lab==='blending'?colorLabView():''}<div class="works">${a.works.map((w,i)=>a.kind==='lesson'?lessonWork(a,w,i):`<section class="work work-${i}"><div class="work-index">${String(i+1).padStart(2,'0')} / SELECTED WORK</div><figure class="archive-photo"><button class="photo-button" data-photo="/assets/${a.id}-${i}.avif" data-caption="${a.name} — ${w[0]} (${w[1]})" aria-label="Enlarge archival image: ${w[0]}"><img src="/assets/${a.id}-${i}.avif" alt="${w[0]} — architectural archive image" loading="lazy"><span class="photo-zoom">＋</span></button><figcaption>${a.name} / Archive plate ${String(i+1).padStart(2,'0')}</figcaption></figure><div class="note-card"><span class="note-pin" aria-hidden="true"></span><h2>${w[0]} <span>(${w[1]})</span></h2><p>${w[2]}</p><span class="note-number">MF—${String(architects.indexOf(a)+1).padStart(2,'0')}.${i+1}</span></div></section>`).join('')}</div>`; }
export function detailView(a) {
 const siblings = groups[a.group].ids.map(id=>byId[id]);
 const next=byId[groups[(a.group+1)%groups.length].ids[0]];
 return `<div class="case-view" data-files="${siblings.length}" style="--case:${a.color};--case-ink:${a.ink||'#f5f2e9'}"><div class="case-heading"><a class="back-link" href="/">← All files</a><span class="case-category">${groups[a.group].title}</span><span class="file-number">FILE ${String(architects.indexOf(a)+1).padStart(2,'0')} / ${String(architects.length).padStart(2,'0')}</span><h1>${a.name}</h1></div><div class="open-folder"><nav class="case-tabs" aria-label="Switch file"><div class="case-tab-stack">${siblings.map(s=>tab(s,s.id===a.id)).join('')}</div></nav><article class="dossier${a.layout==='color'?' lesson-dossier color-dossier':a.layout==='flight'?' flight-dossier':a.layout==='racing'?' racing-dossier':a.kind==='lesson'?' lesson-dossier':''}" aria-label="${a.name} archive"><span class="binding" aria-hidden="true"></span>${a.layout==='color'?colorContent(a):a.layout==='flight'?flightContent(a):a.layout==='racing'?racingContent(a):standardContent(a)}${a.references?`<aside class="lesson-references" aria-label="参考资料"><h2>继续阅读</h2>${a.references.map(([label,url])=>`<a href="${url}" target="_blank" rel="noreferrer">${label} ↗</a>`).join('')}</aside>`:''}<div class="document-end"><span>END OF FILE</span><span>${a.name} · ${a.kind==='lesson'?`${a.topic||'摄影'}学习笔记`:a.years}</span></div></article><div class="case-bottom"><a href="/" class="close-file">Close this file <span>×</span></a><a href="/cases/${next.id}" class="next-file"><small>NEXT COLLECTION</small>${next.name} <span>↗</span></a></div>${footer()}</div>${nextPreview(next)}</div>`;
}
export function aboutView() {
 return `<article class="about-page curiosity-about"><a class="back-link" href="/">← 返回档案柜</a><p class="eyebrow">MCLARY‘S FILES / AN OPEN-ENDED ARCHIVE</p><h1>STAY CURIOUS.<br>KEEP EXPLORING.</h1><div class="about-desk" aria-label="从问题、观察到实践的笔记"><div class="about-sheet"><span class="desk-index">FIELD NOTES / 随手记录</span><h2>从一个<br>「为什么」开始。</h2><p>把想弄明白的事留下来，<br>给新的发现留一点位置。</p><div class="desk-rule"></div><span class="desk-mark">想法未完，待续 ↗</span></div><div class="about-memo"><span>NOTE TO SELF</span><p>保持好奇。<br>允许修改。<br>记得动手试试。</p><span class="memo-arrow" aria-hidden="true">↗</span></div></div><div class="about-story"><p class="lead">这里是 MCLARY 的开放式档案柜，收着值得追问的问题，也收着慢慢弄明白的过程。</p><p>读到的观点、观察到的细节、亲手试过的方法，都可以成为一页笔记。内容会随着兴趣和理解不断整理、补充与改写；文件夹只是暂时的归处，新的联系随时可能发生。</p><p>用文件夹、纸张、图示和便利贴来组织这些记录，是希望浏览也能像翻阅桌上的笔记：可以顺着读，可以来回比较，也可以从偶然感兴趣的一页开始。</p><div class="about-principles"><section><span>01 / 留下问题</span><h2>不急着知道全部</h2><p>从一个具体的疑问出发，先观察，再寻找解释。</p></section><section><span>02 / 试一试</span><h2>让理解有个落点</h2><p>把读到的东西变成小实验，在实践中发现遗漏。</p></section><section><span>03 / 再回来</span><h2>给答案留余地</h2><p>允许旧笔记被修订，也允许兴趣带来新的方向。</p></section></div><h2 class="about-entry-title">从一个文件夹开始</h2><div class="about-groups">${groups.map(g=>`<a href="/cases/${g.ids[0]}" style="--folder:${g.color};color:${byId[g.ids[0]].ink||'#f5f2e9'}"><span>${g.title}</span><small>打开这一组笔记 ↗</small></a>`).join('')}</div><p class="credits">文件夹交互与视觉形式参考 <a href="https://www.mosbyfiles.com/" target="_blank" rel="noreferrer">Mosby’s Files</a>，原网站由 <a href="https://tubikstudio.com/works/mosbyfiles" target="_blank" rel="noreferrer">Tubik Studio</a> 设计。本网站围绕个人学习与探索重新整理内容。</p><a class="return-archive" href="/">继续探索 ↗</a></div>${footer()}</article>`;
}
export function notFoundView() { return `<div class="not-found"><span>FILE NOT FOUND</span><h1>This drawer is empty.</h1><a href="/">Return to the archive</a></div>`; }
